name: Build Chain

on: [pull_request]

jobs:
  build-chain:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [8]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: Maven Build
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build Chain ${{ matrix.java-version }}
        id: build-chain
        uses: kiegroup/github-action-build-chain@treat_env_variables
        with:
          definition-file: https://raw.githubusercontent.com/${GROUP}/${PROJECT_NAME}/${BRANCH}/.ci/pull-request-config.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
