name: Build Chain

on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: Test Artifacts
    steps:
      - name: Build Chain
        id: build-chain
        uses: ginxo/github-action-build-chain@BXMSPROD-989
        with:
          build-command: |
            echo "." > file1.txt
            echo "." > file2.txt
            echo "." > file3.txt
            exit 125
          workflow-file-name: "pull_request.yml"
          archive-artifacts-path: |
            **/file1.txt@always
            **/file2.txt
            **/file3.txt@failure
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"